version: "3.8"
services:
  mongo:
      image: mongo
      container_name: pequena-cozinheira-pedidos
      volumes:
          - /mongodb-pedidos-pequenacozinheira:/data/db
      expose:
          - 27017
      ports:
          - "27017:27017"
  app:
      build: .\
      image: app-pequena-cozinheira
      ports: 
        - "443:443"